# Generated by Django 5.0.4 on 2026-04-07 13:49

import django.db.models.deletion
from django.db import migrations, models


def fill_seller_codes(apps, schema_editor):
    Seller = apps.get_model('users', 'Seller')
    for seller in Seller.objects.order_by('id'):
        seller.seller_code = str(seller.id).zfill(5)
        seller.save(update_fields=['seller_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_label_code'),
        ('users', '0002_sellerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_code',
            field=models.CharField(blank=True, max_length=5, default=''),
        ),
        migrations.RunPython(fill_seller_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='seller',
            name='seller_code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='SellerLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('unused', 'İstifadə edilməyib'), ('used', 'İstifadə edilib')], default='unused', max_length=10)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='users.seller')),
            ],
            options={
                'ordering': ('seller', 'label_number'),
            },
        ),
    ]
