# Generated by Django 5.0.4 on 2026-04-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seller_seller_code_sellerlabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerlabel',
            options={'ordering': ('seller', 'number')},
        ),
        migrations.RenameField(
            model_name='sellerlabel',
            old_name='label_number',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='sellerlabel',
            unique_together={('seller', 'number')},
        ),
        migrations.RemoveField(
            model_name='sellerlabel',
            name='code',
        ),
    ]
