# Generated by Django 5.0.4 on 2026-04-06 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıxış')], max_length=3)),
                ('reason', models.CharField(choices=[('seller_delivery', 'Satıcı təhvil verdi'), ('order_shipped', 'Sifariş göndərildi'), ('return', 'Geri qaytarma'), ('adjustment', 'Düzəliş'), ('damage', 'Zədə / itki')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
