# Generated by Django 5.0.4 on 2026-04-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
