# Generated by Django 5.0.4 on 2026-03-31 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('bike', 'Velosiped'), ('motorcycle', 'Motosiklet'), ('car', 'Avtomobil'), ('foot', 'Piyada')], default='motorcycle', max_length=20)),
                ('zone', models.CharField(choices=[('sumgayit', 'Sumqayıt'), ('baku', 'Bakı'), ('both', 'Hər ikisi')], default='sumgayit', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
